"""
One-time codegen: dumps the mel filterbank and Hann window as C arrays so
the ESP32-S3 firmware computes bit-for-bit the same features as training,
without needing runtime trig/log-mel derivation on-device.
"""
import numpy as np
from features import build_mel_filterbank, N_MELS, N_FFT, FRAME_LEN, _HANN

fb = build_mel_filterbank()  # (N_MELS, N_FFT//2+1)
n_bins = N_FFT // 2 + 1

lines = [
    "// Auto-generated by generate_c_constants.py -- do not edit by hand.",
    "#ifndef TINYML_ANC_CONSTANTS_H_",
    "#define TINYML_ANC_CONSTANTS_H_",
    "",
    f"#define TINYML_N_MELS {N_MELS}",
    f"#define TINYML_N_FFT {N_FFT}",
    f"#define TINYML_N_FFT_BINS {n_bins}",
    f"#define TINYML_FRAME_LEN {FRAME_LEN}",
    "",
    f"// Hann window, length {FRAME_LEN}",
    f"static const float g_hann_window[{FRAME_LEN}] = {{",
]
lines.append("  " + ", ".join(f"{v:.8f}f" for v in _HANN) + "")
lines.append("};")
lines.append("")
lines.append(f"// Mel filterbank, shape ({N_MELS}, {n_bins}), row-major")
lines.append(f"static const float g_mel_filterbank[{N_MELS}][{n_bins}] = {{")
for row in fb:
    lines.append("  {" + ", ".join(f"{v:.8f}f" for v in row) + "},")
lines.append("};")
lines.append("")
lines.append("#endif  // TINYML_ANC_CONSTANTS_H_")

with open("tinyml_anc_constants.h", "w") as f:
    f.write("\n".join(lines))

print("Wrote tinyml_anc_constants.h")
print(f"Hann window: {FRAME_LEN} floats (~{FRAME_LEN*4} bytes)")
print(f"Mel filterbank: {N_MELS}x{n_bins} floats (~{N_MELS*n_bins*4} bytes)")
