// components/tinyml_control/include/tinyml_features.h
//
// C++ port of features.py's log-mel spectrogram extraction, for the
// ESP32-S3. Uses esp-dsp for the FFT (radix-2 complex) and the
// pre-generated constants in tinyml_anc_constants.h (Hann window + mel
// filterbank) so this produces BIT-COMPATIBLE features with training --
// do not hand-tune the math here without regenerating
// tinyml_anc_constants.h from features.py first.
//
// Audio contract: 16 kHz mono, int16 PCM from the primary mic channel,
// AFTER Stage 0's kurtosis impulse filter (see src/impulse.py) has
// already run -- this module does not do impulse rejection itself.

#pragma once

#include <cstdint>
#include <cstddef>

#define TINYML_SAMPLE_RATE   16000
#define TINYML_WINDOW_MS     300
#define TINYML_HOP_MS        100
#define TINYML_FRAME_STEP_MS 10

#define TINYML_WINDOW_SAMPLES  ((TINYML_SAMPLE_RATE * TINYML_WINDOW_MS) / 1000)  // 4800
#define TINYML_HOP_SAMPLES     ((TINYML_SAMPLE_RATE * TINYML_HOP_MS) / 1000)     // 1600
#define TINYML_FRAME_STEP      ((TINYML_SAMPLE_RATE * TINYML_FRAME_STEP_MS) / 1000) // 160
#define TINYML_N_FRAMES        (1 + (TINYML_WINDOW_SAMPLES - TINYML_FRAME_LEN) / TINYML_FRAME_STEP) // 28

// TINYML_FRAME_LEN, TINYML_N_MELS, TINYML_N_FFT, TINYML_N_FFT_BINS come
// from tinyml_anc_constants.h (generated by generate_c_constants.py)
#include "tinyml_anc_constants.h"

class TinyMLFeatureExtractor {
public:
    TinyMLFeatureExtractor();
    ~TinyMLFeatureExtractor();

    // Call once at startup. Returns false on FFT-table init failure.
    bool init();

    // Push TINYML_HOP_SAMPLES of new int16 mic audio (post Stage-0 filter).
    // Internally maintains a TINYML_WINDOW_SAMPLES rolling buffer.
    void push_audio(const int16_t *samples, size_t n);

    // Computes the (TINYML_N_FRAMES x TINYML_N_MELS) log-mel feature map
    // for the current rolling buffer contents and writes it, ALREADY
    // per-utterance normalized (mean 0, std 1) to match training, into
    // `out_features` (must hold TINYML_N_FRAMES * TINYML_N_MELS floats,
    // row-major [frame][mel]).
    void compute_features(float *out_features);

private:
    float audio_buffer_[TINYML_WINDOW_SAMPLES];   // rolling float audio, [-1, 1]
    float fft_buf_[TINYML_N_FFT * 2];             // interleaved re/im for esp-dsp
    bool fft_initialized_ = false;
};
